### ISSUE TITLE
Missing script

### ISSUE THREAD

**Issue by fefemess** [dpgraham4401/dotfiles-sway#1]
mediaplayer script is missing, would be nice to be able to use it

**Comment by dpgraham4401** [comment]
Hi @fefemess, can you clarify? I'm using playerctl to control media, no script 
https://github.com/dpgraham4401/dotfiles-sway/blob/master/.config/sway/config

    ## Volume
    bindsym XF86AudioRaiseVolume exec pactl set-sink-volume @DEFAULT_SINK@ +5%
    bindsym XF86AudioLowerVolume exec pactl set-sink-volume @DEFAULT_SINK@ -5%
    bindsym XF86AudioMute exec pactl set-sink-mute @DEFAULT_SINK@ toggle
   
    # Media playerctl  
    bindsym XF86AudioNext exec playerctl next
    bindsym XF86AudioPrev exec playerctl previous
    bindsym XF86AudioPlay exec playerctl play-pause

**Comment by fefemess** [comment]
@dpgraham4401 Yeah i'm talking about waybar's media control script

**Comment by dpgraham4401** [comment]
@fefemess that's part of waybar's default config files and resources which [can be found here](https://github.com/Alexays/Waybar/tree/master/resources/custom_modules)
