### ISSUE TITLE
How to get your wallpaper?

### ISSUE THREAD

**Issue by n0yal** [dpgraham4401/dotfiles-sway#2]
I need your wallpaper so the waybar looks like you

**Comment by dpgraham4401** [comment]
I'm using a couple different wallpapers. the fedora 34 one can be found online here https://fedoraproject.org/wiki/Wallpapers#Fedora_34

I've also used a couple at the top of this page  https://wallpapercave.com/fedora-linux-wallpaper

I can't find the last one, but it was somewhere on wallpapercave.com, lots of good stuff on there. 
![cute_rocket](https://user-images.githubusercontent.com/43794491/127640631-a0599d0a-898e-4ed6-a17a-d3a124b6d81e.png)
